### ISSUE TITLE
Issue with evaluation

### ISSUE THREAD

**Issue by cynicalsavant** [kaanakan/slamp#5]
https://github.com/kaanakan/slamp/blob/7c47e6b561d1f973626061d8e8600e072ed6785e/helpers.py#L367

This line causes an issue with evaluation pipeline and results in faulty scores. The correction should be
`gen_seq, gt_seq = [], []`

**Comment by kaanakan** [comment]
Hello, thanks for letting us know. 
We just found out that there is a specific pull request (#4) that corrects the reported problem.
The solution does not affect the reproducibility of the work.
We merged it.
